/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Board {
  key: string;
  name: string;
  members?: {
    [k: string]: any;
  }[];
  created?: number;
  avatar?: string;
}
