export const MENU = [{
  label: 'Contacts',
  icon: 'users',
  route: ['/contacts']
}, {
  label: 'Invoices',
  icon: 'file-invoice-dollar',
  route: ['/invoices']
}, {
  label: 'Orders',
  icon: 'shopping-cart',
  route: ['/orders']
}, {
  label: 'Payments',
  icon: 'exchange-alt',
  route: ['/transactions']
}, {
  label: 'Accounts',
  icon: 'piggy-bank',
  route: ['/accounts']
}, {
  label: 'Contracts',
  icon: 'signature',
  route: ['/agreements']
}, {
  label: 'Storage',
  icon: 'warehouse',
  route: ['/storage']
}, {
  label: 'Files',
  icon: 'folder-open',
  route: ['/files']
}, {
  label: 'Notes',
  icon: 'sticky-note',
  route: ['/notes']
}, {
  label: 'Projects',
  icon: 'project-diagram',
  route: ['/projects']
}, {
  label: 'Boards',
  icon: 'comments',
  route: ['/boards']
}, {
  label: 'Present',
  icon: 'desktop',
  route: ['/presentations']
}, {
  label: 'Analytics',
  icon: 'chart-pie',
  route: ['/analytics'],
  disabled: true
}]
